# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  lint-commit:
    name: lint (commit)
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm install --save-dev @commitlint/{config-conventional,cli} commitlint-plugin-jira-rules commitlint-config-jira
      - name: Add dependencies for commitlint action
        run: echo "NODE_PATH=$GITHUB_WORKSPACE/node_modules" >> $GITHUB_ENV
      - run: git remote add upstream https://github.com/lux-org/lux
      - run: git fetch upstream
      - run: npx commitlint --from upstream/master --to $(git log upstream/master..HEAD --pretty=format:"%h" | tail -1) --verbose
  pre-commit:
    name: Check pre-commit hooks
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: pre-commit/action@v2.0.3
  build:

    runs-on: ubuntu-latest

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: lux
          POSTGRES_DB: postgres
        # Set health checks to wait until postgres has started
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jupyter-client==6.1.6
        pip install wheel
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        pip install sqlalchemy

        # pip uninstall -y  lux-widget
        # pip install git+git://github.com/lux-org/lux-widget.git
        # # Temporary Fix (#372)
        # cd /opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/luxwidget/
        # mkdir labextension
        # cd labextension
        # wget https://raw.githubusercontent.com/lux-org/lux-widget/master/luxwidget/nbextension/package.json

    - name: Upload data to Postgres
      run: |
        python lux/data/upload_car_data.py
        python lux/data/upload_aug_test_data.py
        python lux/data/upload_airbnb_nyc_data.py
    - name: Test with Pytest and Code Coverage Report
      run: |
        pytest --cov-report term --cov=lux tests/ tests_sql/
        bash <(curl -s https://codecov.io/bash)
